# Generated by Django 3.0.5 on 2020-05-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_swimmer_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Male', max_length=1),
        ),
    ]
