# Generated by Django 3.0.5 on 2020-05-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200501_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmer',
            name='gender',
            field=models.CharField(choices=[('CH', 'Choose a Gender'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='CH', max_length=2),
        ),
    ]
