# Generated by Django 3.0.5 on 2020-05-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200501_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmer',
            name='birthday',
            field=models.DateField(),
        ),
    ]
