# Generated by Django 3.0.5 on 2020-05-02 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20200501_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmer',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
