# Generated by Django 3.0.5 on 2020-05-02 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200501_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swimmer',
            name='birthday',
        ),
    ]
