# Generated by Django 3.0.5 on 2020-05-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_remove_swimmer_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmer',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
    ]
