# Generated by Django 3.0.5 on 2020-05-02 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_swimmer_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swimmer',
            name='age',
        ),
    ]
