# Generated by Django 3.0.6 on 2020-05-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_swimmer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmer',
            name='gender',
            field=models.CharField(choices=[('N', 'Select...'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='N', max_length=2),
        ),
    ]
